# Generated by Django 3.0.4 on 2020-03-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='upload_date_time',
            new_name='upload_date',
        ),
    ]
